### ISSUE TITLE
Shared species in case of one community is a subset of the other one: problem with 'Chaoshared'

### ISSUE THREAD

**Issue by PhilippeJeanneret** [AnneChao/SpadeR#1]
Dear Anne,
I used SpadeR and tried to calculate the number of shared species in two communities. There are things which seem strange. I already asked Johnson but have got no reply till now.
With two communities like this:
`test <- data.frame(x = 1:20, y = c(0,0,0,0,0,2,4:17))`
`ChaoShared(test, datatype="abundance", se=TRUE, nboot=200, conf=0.95)`
 I got that error message:
**Error in rmultinom(B, n2, p2) : NA in probability vector**
 Note that the community "x" has no 0 abundances (all "y" species are occurring in "x").

In contrast, by doing that:
 `test <- data.frame(x = c(1:15,0,0,0,0,0), y = c(0,0,0,0,0,2,4:17))`
 `ChaoShared(test, datatype="abundance", se=TRUE, nboot=200, conf=0.95)`
I got normal results.
I have tested with several pairs of communities and my conclusion is if one community is a subset of the second one, i.e. one community has no 0 occurences, 'ChaoShared' cannot calculate. Of course, the number of shared species is then the number of species of the smallest community but it would be nice to get estimates and SE.
Is that feasible ?

Thank you in advance for your reply.
Best wishes,
Philippe

**Comment by PhilippeJeanneret** [comment]
Dear Anne and Johnson,

... any news regarding the comment I posted in November 2015?
Best regards,
Philippe

**Comment by PhilippeJeanneret** [comment]
Dear Anne,
Further testing of 'ChaoShared' showed me difficult failures to understand:
`test <- data.frame(v1 = c(1,1,0,0), v2 = c(1,0,1,1))`
`ChaoShared(test, datatype="abundance", se=TRUE, nboot=200, conf=0.95)`
gives outputs but this: 
`data.frame(v1 = c(1,1,0,1), v2 = c(1,0,1,0))`
results in "**Error in rmultinom(B, n2, p2) : NA in probability vector
Called from: rmultinom(B, n2, p2)**"
Quite strange, isn't it? In both cases, both communities have 1 species shared (the first one), one community has 1 exclusive species and the other community has 2 exclusive species.
I hope you can help me to understand, respectively resolve the problem.
Thanks in advance for your answer.
Best regards,
Philippe

**Comment by AnneChao** [comment]
Philippe,
Thank you for your query and sorry for the late reply as this is our busy
end-semester season.
The problem you encountered with Spade was because your data are too
sparse. For example, if you only have two species in Sample I and three
species in Sample II, any statistical method cannot work on such sparse
data. For estimating shared species, we need at least 20 or better 30
species in each sample. As an oriental saying: even a smart housewife
cannot make a meal with rice. Your data are not sufficient.
Hope these are of help.
Best, Anne

2015-11-25 19:08 GMT+08:00 PhilippeJeanneret notifications@github.com:

**Comment by PhilippeJeanneret** [comment]
Dear Anne,
Thank you for considering my mail.
I know that no statistics can be derived from communities with three or four species.
However, I was not confident in the code "ChaoShared" when seeing that the ranking of species occurrences in two communities did have an impact on the result, see my previous comment.
I further checked with larger communities and was happy to see reasonable results.
The question remains about how many species must the communities have to give reasonable results in the sense that the ranking of the species has no impact on the functioning of "ChaoShared"?
Furthermore, I still remain surprised to not have "ChaoShared" working when one community is a subset of the second one:
test <- data.frame(v1 = c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1), v2 = c(0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1))
ChaoShared(test, datatype="abundance", se=TRUE, nboot=200, conf=0.95)
Any comment on that?
Thank you in advance.
Philippe
Error in rmultinom(B, n2, p2) : NA in probability vector
Called from: rmultinom(B, n2, p2)
Browse[1]> Q
