### ISSUE TITLE
Two-Community Similarity Index: Error in correct_obspi(X1) : object 'a' not found

### ISSUE THREAD

**Issue by Es-aqua** [AnneChao/SpadeR#6]
Hi,

I am using SpadeR for calculating two-Community Similarity Index for the following matrix: 
 [,1] [,2]
 [1,]    2    0
 [2,]  211  184
 [3,]    8    5
 [4,]    2    0
 [5,]    2    0
 [6,]   70   72
 [7,]    8    2
 [8,]    2    0
 [9,]    0    1
[10,]   10    8
[11,]    3    5
[12,]  320   81
[13,]    4    4
[14,]    4    0
[15,]    5    3
[16,]   19    0

My code is as below:
B <- matrix(c(2, 211, 8, 2, 2, 70, 8, 2, 0, 10, 3, 320, 4, 4, 5, 19, 0, 184, 5, 0, 0, 72, 2, 0, 1, 8, 5, 81, 4, 0, 3, 0), nrow=16, ncol=2) 
SimilarityPair(B, datatype="abundance", nboot=200)

An error message is returned: 
Error in correct_obspi(X1) : object 'a' not found 

I have run the same code for other similar data pairs with no problem, and I am wondering if you would have any idea of what is at stake here?

Thanks a lot.

**Comment by AnneChao** [comment]
Thanks for using our program SpadeR and ​sending feedback.

Your problem ​has been resolved. 

Please re-download the ​just-modified ​program SpadeR and ​re-run your data.

Any ​further comments are welcome.

**Comment by Es-aqua** [comment]
Thank you very much for your time and help.
